version: "3.1"

services:
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker_1:
    build:
      context: ./base
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M  
          cpus: '1'    
    image: daskdev/dask
    hostname: dask-worker
    volumes:
      - /Users/carlo.scarioni/Downloads/taxi-data/:/data
    command: ["dask-worker", "tcp://scheduler:8786", "--nprocs", "1", "--nthreads", "3", "--memory-limit", "2000000000"]

  worker_2:
    build:
      context: ./base
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M 
          cpus: '1' 
    image: daskdev/dask
    hostname: dask-worker2
    volumes:
      - /Users/carlo.scarioni/Downloads/taxi-data/:/data
    command: ["dask-worker", "tcp://scheduler:8786", "--nprocs", "1", "--nthreads", "3", "--memory-limit", "2000000000"]

  worker_3:
    build:
      context: ./base
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M  
          cpus: '1'
    image: daskdev/dask
    hostname: dask-worker3
    volumes:
      - /Users/carlo.scarioni/Downloads/taxi-data/:/data
    command: ["dask-worker", "tcp://scheduler:8786", "--nprocs", "1", "--nthreads", "3", "--memory-limit", "2000000000"]
      
  worker_4:
    build:
      context: ./base
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M  
          cpus: '1'
    image: daskdev/dask
    hostname: dask-worker4
    volumes:
      - /Users/carlo.scarioni/Downloads/taxi-data/:/data
    command: ["dask-worker", "tcp://scheduler:8786", "--nprocs", "1", "--nthreads", "3", "--memory-limit", "2000000000"]
        
  worker_5:
    build:
      context: ./base
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2048M  
          cpus: '1'
    image: daskdev/dask
    hostname: dask-worker5
    volumes:
      - /Users/carlo.scarioni/Downloads/taxi-data/:/data
    command: ["dask-worker", "tcp://scheduler:8786", "--nprocs", "1", "--nthreads", "3", "--memory-limit", "2000000000"]
  

  base-notebook:
    build:
      context: github.com/jupyter/docker-stacks.git#master:base-notebook
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.8"
    image: jupyter/base-notebook:lab

  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: daskdev/dask-notebook
    depends_on:
      - base-notebook
    hostname: notebook
    ports:
      - "8888:8888"
    volumes:
      - /Users/carlo.scarioni/Downloads/taxi-data/:/data  
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
